server:
  port: 9001

spring: 
  datasource: 
    url: ${JDBC_DATABASE_URL} 
#jdbc:postgresql://localhost:5432/dbtest 
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME} 
#dbuser
    password: ${JDBC_DATABASE_PASSWORD}
#lizo90
  jpa: 
    hibernate: 
      ddl-auto: create 
 
# ${JDBC_DATABASE_URL} 
# ${JDBC_DATABASE_USERNAME}
# ${JDBC_DATABASE_PASSWORD
  
