server:
  port: 9001

#spring:
#  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
##jdbc:postgresql://localhost:5432/dbtest
##dbuser
##lizo90
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  data:
    mongodb:
      uri: "mongodb://admin:lizo90@ds223542.mlab.com:23542/khweladb"
  
