server:
  port: 9001
flyway:
  baselineOnMigrate: true
  enabled: true
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
#jdbc:postgresql://localhost:5432/dbtest 
#dbuser
#lizo90
  jpa: 
    hibernate: 
      ddl-auto: update
